version: '3.4'

services:
  api:
    image: your-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Port=5432;Username=postgres;Password=1234;Database=MarcasAutoDb
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: MarcasAutoDb
    ports:
      - "5432:5432"